### ISSUE TITLE
HPBar affected by freeze/PowerTimeFreezer

### ISSUE THREAD

**Issue by MrSatan6666** [0Eagle/hpbar#2]
HPBar's health bar stops functioning when you use the freeze console command or PowerTimeFreezer is active.
Giving the +NOTIMEFREEZE flag to hpbar-testing-puff-base fixes this problem.  Tested in NET, no noticeable desyncs.

**Comment by 0Eagle** [comment]
already fixed it. I'm waiting for zandronum 3.1, the latest improvements of the mod require it.

**Comment by 0Eagle** [comment]
hpbar-v24d
